# Port (optional)
#server.port=8080

# Allow both /secrets and /secrets/ to match
spring.mvc.trailing-slash-match=true
api.url=https://gps-backend-h7cw.onrender.com
get.location.gps.url=https://gpssoftware.in/web_api/api/ShareLocation/GetLastLocation/
#api.url=http://localhost:8080

# Token required to update secrets
app.update.token=aad@03